<div class="jumbotron">
    <h1>Aplikacja do udostępniania zbiorów muzealnych online</h1>
    Aktualna wersja aplikacji to 0.00000001 ultra.pre.alfa<br/>
    
    <p>
        Witaj Drogi Użytkowniku.<br />
        Składamy do twoich rąk narzędzie do prezentacji twoich zbiorów, zarządzania metadanymi, wyszukiwania ich oraz sprzedawania. <br />
        
        
    </p>

    <p><a class="btn btn-success btn-lg" href="https://github.com/Hubkot/MuseumCollectionViewer/" target="_blank">Pobierz wprost z Githuba &raquo;</a></p>
</div>

<div class="row">

    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Aktualności</h3>
            </div>
            <div class="panel-body">
                <p>
                    Właśnie podmieniono layout główny aplikacji.
                </p>
                <br>
                <p><a class="btn btn-success pull-right" href="">Lista zmian /nieaktywne/ &raquo;</a></p>
            </div>
        </div>
    </div>

    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Panel dla przeglądającego</h3>
            </div>
            <div class="panel-body">
                <p>
                    Z tego miejsca będziemy przenosili odwiedzającego w głąb aplikacji.
                </p>
                <br>
                <p><a class="btn btn-success pull-right" href="" target="_blank">Przeglądaj zasoby /nieaktywne/ &raquo;</a></p>
            </div>
        </div>
    </div>

    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Dokumentacja</h3>
            </div>
            <div class="panel-body">
                <p>
                    Tu zamieścimy dokumentację aplikacji, aby każdy kto chce ją zainstalować dostał jasną instrukcję krok po kroku.
                </p>
                <br/>
                <p><a class="btn btn-success pull-right" href="" target="_blank">Dokumentacja MCV</a></p>
            </div>
        </div>
    </div>
</div>
