#services:
#    mcv_admin.example:
#        class: McvAdminBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]

assetic:
    debug:            "%kernel.debug%"
    use_controller:   "%kernel.debug%"
    filters:
        cssrewrite: ~
    assets:
        admin_css:
            inputs:
                - '@McvAdminBundle/Resources/public/admin.css'
parameters:
   shared_dir: %kernel.root_dir%/../web/shared         
   upload_dir: %kernel.root_dir%/../web/upload         