<?php

namespace McvBundle\Repository;

/**
 * ArtifactTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArtifactTypeRepository extends \Doctrine\ORM\EntityRepository
{
}
