<?php

namespace McvAdminBundle\Repository;

use Doctrine\ORM\EntityRepository;
use McvAdminBundle\Entity\ArtifactFiles;

/**
 * ArtifactFilesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArtifactFilesRepository extends EntityRepository
{
    public function isExist($filename){
        if($this->findBy(['filename' => $filename])){
            return true;
        }
        else{
            return false;
        }
    }
    public function importFiles($foundedFilesArray,$entityManager){
         
        foreach ($foundedFilesArray as $f){
           if(!$this->isExist($f['filename'])){
               $file = new ArtifactFiles();
               $file->setFilename($f['inventory_number'].'_'.$f['photo_number'].'_'.$f['category_symbol'].'.'.$f['file_extension']);
               $file->setFilepath($f['inventory_number'].'/date/');
               $file->setPhotoNumber($f['photo_number']);
               $file->setCategorySymbol($f['category_symbol']);
               $entityManager->persist($rekord);
               echo 'Tworzę rekord <br />';
           }
           elseif($this->isExist($f['filename'])){
               echo 'Rekord istnieje. Nie robię nic dalej<br />';
               }
          else{
              echo 'Wykryto błąd aplikacji';
          }
         
        }
        $entityManager->flush();
        return; 
    }
}
