<?php

namespace McvAdminBundle\Repository;

/**
 * ArtifactDescriptionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArtifactDescriptionRepository extends \Doctrine\ORM\EntityRepository
{
 
}
