<?php

namespace McvAdminBundle\Repository;

/**
 * ArtifactFileRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArtifactFileRepository extends \Doctrine\ORM\EntityRepository
{
    
}
